title: Hands-On UNIX System Administration DeCal
shorttitle: UNIX SysAdmin DeCal
email: decal@ocf.berkeley.edu
description: >-
  The OCF's SysAdmin DeCal at UC Berkeley.
baseurl: ""
url: "https://decal.ocf.berkeley.edu"

# Build settings
markdown: kramdown

include:
  - ".htaccess"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

