title: Hands-On Linux System Administration DeCal
shorttitle: Linux SysAdmin DeCal
email: decal@ocf.berkeley.edu
description: >-
  The OCF/XCF Linux SysAdmin DeCal at UC Berkeley
baseurl: ""
url: "https://decal.ocf.berkeley.edu"

# Build settings
markdown: kramdown

include:
  - ".htaccess"

# A list of files or directories to exclude from processing when building the
# site, like any dependency management files, build files, etc.
exclude:
  - Gemfile
  - Gemfile.lock
  - Jenkinsfile
  - LICENSE
  - Makefile
  - README.md
  - vendor/bundle/
